version: '3'

services:
  db:
    image: 'postgres:16.2'
    container_name: portfolio-db
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: 'redis:7.2.4'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-sentinel-1:
    image: 'bitnami/redis-sentinel:7.0.15'
    container_name: redis-sentinel-1
    environment:
      - REDIS_MASTER_SET=redis
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
    links:
      - redis

  web:
    build: .
    container_name: portfolio
    command: bin/rails s -b 0.0.0.0
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - redis-sentinel-1
    ports:
      - '3000:3000'
    volumes:
      - '.:/var/www/porfolio'
    environment:
      - PORTFOLIO_DATABASE_PASSWORD=postgres

volumes:
  postgres:
